### ISSUE TITLE
请问BM什么时候能支持WebGL呢

### ISSUE THREAD

**Issue by whl160118** [mister91jiao/BundleMaster#9]
如题

**Comment by lywedo** [comment]
邮件已收到，谢谢

**Comment by mister91jiao** [comment]
下个版本将会支持WebGL，如果WebGL比较着急也可以现在联系我，改几个地方就可以了

**Comment by whl160118** [comment]
> 下个版本将会支持WebGL，如果WebGL比较着急也可以现在联系我，改几个地方就可以了

有点着急 我们有个小项目 月底想发布WebGL平台 准备用BM 能给我说下具体改哪几个地方吗
